#!/bin/env python3

# sockv5
SOCK_V5 = 5
RSV = 0
ATYP_IP_V4 = 1
ATYP_DOMAINNAME = 3
CMD_CONNECT = 1
IMPLEMENTED_METHODS = (0, )

# websocket
WEBSOCKETS_MAX_QUEUE = 2 ** 10

# nmp
NMP_CONNECT_OK = 0
NMP_CONNECT_FAILED = 1
NMP_TCP_PIPE_IP = ATYP_IP_V4
NMP_TCP_PIPE_DOMAIN = ATYP_DOMAINNAME
NMP_UDP_PIPE_IP = 4

NMP_FASTPATH_HOST = 'Nmp-Fastpath-Host'
NMP_FASTPATH_PORT = 'Nmp-Fastpath-Port'
NMP_FASTPATH_PAYLOAD = 'Nmp-Fastpath-Payload'
NMP_FASTPATH_MAX_BYTES = 4 * 1024